// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct PROPERTY_TYPE_Agent_Dominant_currentLane { };
template<> inline LaneIdx& Agent_Dominant::_Get_Property_<PROPERTY_TYPE_Agent_Dominant_currentLane>()
{
	return this->currentLane;
}

struct PROPERTY_TYPE_Agent_Dominant_currentState { };
template<> inline DriveState& Agent_Dominant::_Get_Property_<PROPERTY_TYPE_Agent_Dominant_currentState>()
{
	return this->currentState;
}

struct PROPERTY_TYPE_Agent_Dominant_lastState { };
template<> inline DriveState& Agent_Dominant::_Get_Property_<PROPERTY_TYPE_Agent_Dominant_lastState>()
{
	return this->lastState;
}

struct PROPERTY_TYPE_Agent_Dominant_systemStatus { };
template<> inline System_Status& Agent_Dominant::_Get_Property_<PROPERTY_TYPE_Agent_Dominant_systemStatus>()
{
	return this->systemStatus;
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
